/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ethContracts from "./ethContracts";
export type { ethContracts };
import type * as polyContracts from "./polyContracts";
export type { polyContracts };
export type { IERC20ChildToken } from "./IERC20ChildToken";
