/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as polySideBridgeSol from "./polySideBridge.sol";
export type { polySideBridgeSol };
export type { PolySideToken } from "./PolySideToken";
