/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ethContracts from "./ethContracts";
export * as polyContracts from "./polyContracts";
export { IERC20ChildToken__factory } from "./IERC20ChildToken__factory";
