/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EthSideBridge__factory } from "./EthSideBridge__factory";
export { EthSideToken__factory } from "./EthSideToken__factory";
