/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Burnable__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "EthSideBridge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EthSideBridge__factory>;
    getContractFactory(
      name: "EthSideToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EthSideToken__factory>;
    getContractFactory(
      name: "IERC20ChildToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20ChildToken__factory>;
    getContractFactory(
      name: "EthSideBridge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EthSideBridge__factory>;
    getContractFactory(
      name: "PolySideBridge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolySideBridge__factory>;
    getContractFactory(
      name: "PolySideToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolySideToken__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC20Burnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Burnable>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "EthSideBridge",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EthSideBridge>;
    getContractAt(
      name: "EthSideToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EthSideToken>;
    getContractAt(
      name: "IERC20ChildToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20ChildToken>;
    getContractAt(
      name: "EthSideBridge",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EthSideBridge>;
    getContractAt(
      name: "PolySideBridge",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PolySideBridge>;
    getContractAt(
      name: "PolySideToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PolySideToken>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
